version: "3.9"

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data/repository:/data/repository
  newsfeed:
    build: .
    ports:
      - "8080:8080"
    environment:
      CONFIG_PATH: "/app/configs/test-config.yaml"
    links:
      - mongo
    depends_on:
      - mongo