http:
  port: 8080
  write_timeout: "10s"  # sec
  read_timeout: "10s"  # sec
logger:
  level: "DEBUG"
  format: "2006-01-02T15:04:05.999999999Z07:00"  # RFC 3339
database:
  host: "127.0.0.1"
  port: 27017
  name: "newsfeed"
hyper_params:
  shutdown_timeout: 10 # sec
